name: SlimefunTexture
version: '${project.version}'
main: club.thornya.slimefuntexture.SlimefunTexture
api-version: '1.20'
authors: [Gusttavo13]
description: Coloca textura no jogador automaticamente
commands:
  textura:
    description: Textura Editor
